import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { ChangeEvent } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const doYOURthing = async (e: ChangeEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const file = formData.get("file");
    if (!file) {
      return;
    }

    // @ts-ignore
    const fileType = encodeURIComponent(file.type);

    const { data } = await axios.get(`/api/hello?fileType=${fileType}`);
    const { uploadURL, key } = data;

    await axios.put(uploadURL, file);

    return key;
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={doYOURthing}>
          <input
            type="file"
            accept="image/jpeg image/png image/svg"
            name="file"
          />
          <button type="submit">submit</button>
        </form>
      </main>
    </div>
  );
}
